2021June-main/MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        private ICastService _castSevice;
        public CastController(ICastService castService)
        {
            _castSevice = castService;
        }
        public async Task<IActionResult> CastDetail(int id)
        {
            var movie = await _castSevice.GetCastDetails(id);
            return View(movie);
        }
    }
}

2021June-main/MovieShopMVC/Controllers/MovieController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace MovieShopMVC.Controllers
{
    public class MovieController : Controller
    {
        private IMovieService _movieService;
        private IGenreService _genreService;
        public MovieController(IMovieService movieService, IGenreService genreService)
        {
            _movieService = movieService;
            _genreService = genreService;
        }
       public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }

        public async Task<IActionResult> Genre(int id)
        {
            var movie = await _genreService.GetTopRevenueMoviesByGenre(id);
            return View(movie);
        }
    }
}

2021June-main/MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.RepositoryInterfaces;
using ApplicationCore.ServiceInterfaces;
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace MovieShopMVC.Controllers
{
    public class UserController : Controller
    {
        private readonly ICurrentUser _currentUser;
        private readonly IMovieService _movieService;
        private readonly IUserRepository _userRepository;
        private readonly IMovieRepository _movieRepository;
        private readonly IPurchaseService _purchaseService;
        private readonly IPurchaseRepository _purchaseRepository;
        public UserController(ICurrentUser currentUser, IMovieService movieService, IPurchaseRepository purchaseRepository,
                              IUserRepository userRepository, IMovieRepository movieRepository, IPurchaseService purchaseService)
        {
            _currentUser = currentUser;
            _movieService = movieService;
            _userRepository = userRepository;
            _movieRepository = movieRepository;
            _purchaseService = purchaseService;
            _purchaseRepository = purchaseRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Purchase(int id)
        {
            
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
            
        }

        public async Task<IActionResult> ConfirmPurchase(int id)
        {
            var userId = _currentUser.UserId;
            var user = await _userRepository.GetByIdAsync(userId);
            var movie = await _movieRepository.GetByIdAsync(id);
            var purchase = new Purchase
            {

                UserId = user.Id,
                TotalPrice = movie.Price.GetValueOrDefault(),
                MovieId = id
                
            };
            
            var createdPurchase = await _purchaseRepository.AddAsync(purchase);
            purchase.Id = createdPurchase.Id;
            return View("ThanksToPurchase");
        }



        // View Profile

        // Edit Profile

        // Library (MyMovieCount)
    }
}

2021June-main/MovieShopMVC/Views/Movie/Details.cshtml
@model ApplicationCore.Models.MovieDetailsResponseModel


@{
    ViewData["Title"] = "Moive Details";
}
<script src="https://kit.fontawesome.com/c74d6832d0.js" crossorigin="anonymous"></script>


<div class="container">
    <div class="row">
        <div class="col">
            <img src=" @Model.PosterUrl">
        </div>
        <div class="col">
            <h2>@Model.Title</h2>
            <p>@Model.Tagline</p>
            <p>@Model.RunTime m | @Model.ReleaseDate.Value.Year     @foreach (var genre in Model.Genres)
            {<span class="badge badge-secondary"> @genre.Name</span>}</p>
            <p>@Model.Rating</p>
            <p>@Model.Overview</p>
        </div>
        <div class="col">
            <ul class="list-group">
                <li class="list-group-item"><button type="button" class="btn btn-dark">Review</button></li>
                <li class="list-group-item"><button type="button" class="btn btn-dark">Trailer</button></li>
                @if (User.Identity.IsAuthenticated)
                {
            
            <li class="list-group-item">
                <a class="btn btn-primary" asp-controller="User" asp-action="Purchase" asp-route-id="@Model.Id"> Buy @Model.Price </a>
                @*<button type="button" class="btn btn-light" asp-controller="User" asp-action="ConfirmPurchase" asp-route-id="@Model.Id">Buy @Model.Price</button>*@
            </li>
                    <li class="list-group-item"><button type="button" class="btn btn-light">Watch Movie</button></li>
                }

            </ul>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <h4>MOVIE FACTS</h4>
            <ul class="list-group">
                <li class="list-group-item "> <i class="fas fa-calendar-week"></i> Release Date: <span class="badge badge-secondary">@Model.ReleaseDate </span></li>
                <li class="list-group-item"> <i class="fas fa-hourglass-half"></i> Run Time: <span class="badge badge-secondary">@Model.RunTime m</span></li>
                <li class="list-group-item"><i class="fas fa-coins"></i> Box Office: <span class="badge badge-secondary">@Model.Revenue</span></li>
                <li class="list-group-item"><i class="fas fa-dollar-sign"></i> Budget: <span class="badge badge-secondary">$@Model.Budget</span></li>
            </ul>
        </div>
        <div class="col">
            <h4>CAST</h4>
            <ul class="list-group">
                @foreach (var cast in Model.Casts)
                {
                    <li class="list-group-item ">
                        <a asp-controller="Cast" asp-action="CastDetail" asp-route-id=@cast.Id>
                            <img src="@cast.ProfilePath" height=100>
                        </a>
                        @cast.Name / @cast.Character
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

2021June-main/MovieShopMVC/Views/Movie/Genre.cshtml
@model List<ApplicationCore.Models.MovieCardResponseModel>

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-3">
                    <partial name="_MovieCard" model="movie" />
                </div>
            }
        </div>
    </div>
</div>